### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by flgdev** [DigitalUkraine/digitalpolice-java#2]
Налаштувати запуск тестів після кожного комміту

**Comment by pubsy** [comment]
Створив fork на репозиторій щоб потестувати Tarvis CI отут: https://github.com/pubsy/digitalpolice-java
У README можна побачити іконку - статус останнього білда. Отаку:
[![Build Status](https://api.travis-ci.org/pubsy/digitalpolice-java.svg?branch=master)](https://travis-ci.org/pubsy/digitalpolice-java)
Білд тригериться на кожний коміт (commit) за допомогою хуків (hook). Для цього Travis CI мусить отримати доступ до групи та репозиторіїв. Доступ я запросив, але це мій особистий обліковий запис у Travis CI. Певно краще було б зареєструватися в Travis CI окремо, для DigitalUkraine.

**Comment by crazyfox-ua** [comment]
Готово: http://162.211.230.155:8181/job/digitalpolice-java/badge/icon
Сам CI: http://162.211.230.155:8181
