### ISSUE TITLE
Configure Spring with Hibernate via JPA API.

### ISSUE THREAD

**Issue by AlexandrBelenov** [DigitalUkraine/digitalpolice-java#20]
It is needed to rewrite code, because now we configure Spring with Hibernate directly. It makes data access level less flexible, because depends of certain ORM realization.

**Comment by vitaliikravets** [comment]
Hello @AlexanderBelenov,
I agree, we should ultimately get rid of all the Hibernate references.
- Is the change targeting ContextConfig only?

I can see that we could get rid of all the db connection beans in that class (DataSource, SessionFactory, HibernateTransactionManager etc.) and switch to the Spring Boot way of configuring DB access layer.
Please take a look at this example:
https://spring.io/guides/gs/accessing-data-jpa/

**Comment by AlexandrBelenov** [comment]
A agree with you to use Spring boot way of configuring DB. Now, I am spending time over this to solve.
