### ISSUE TITLE
Helper для виводу у форматі GeoJSON

### ISSUE THREAD

**Issue by flgdev** [DigitalUkraine/digitalpolice-java#3]
Створити клас CrimeDTO, структура якого буде аналогічною до [GeoJSON](http://geojson.org/).

Також створити клас Helper в пакеті util, і метод transform у ньому, який буде примати List < Crime > і повертати List < CrimeDTO >

**Comment by vitaliikravets** [comment]
Закомітив GeoJSON репрезентацію для злочинів. Поревьювайте хто не будь будь ласка.
