### ISSUE TITLE
Вивід дати в УРЛ

### ISSUE THREAD

**Issue by velmyshanovnyi** [DigitalUkraine/digitalpolice-java#5]
даний формат видачі в dateFrom / dateTo  =

замінити на стандарт
2016-12-31 23:58:59
2016-12-31 (в разі відсутності часу годин/хвилин)
23:58:59 (в разі відсутності дати)

dateFrom / dateTo - дати
timeFrom / timeTo - часу

по реалізації записати в файлик з АПІ

**Comment by velmyshanovnyi** [comment]
навіщо?
бо УРЛи при "/" часто ламаються

**Comment by flgdev** [comment]
Потрібна більш чітка мотивація. Особливо для того щоб розбити поле dateFrom(To) на date + time.
